### PR TITLE
Duplicate terms with unique IDs

### PR DESCRIPTION
**Pull request by Wred**
Hi Teng, I've added the ability to have duplicate terms with distinct IDs.  I need this in my case where I have many artists with the same name but different IDs.

### CODE REVIEW

**Comment by Wred** [comment]
Hiya, I've been using this module with my latest fixes for a while now and it works great.  Hopefully, you can accept these changes and include it in the npm repo.  The module is more or less complete.

**Comment by sssionggg** [comment]
Hi @Wred,

Sorry.  Apparently, I am not getting any notification about pull requests.  Sorry.  Should push this out soon.

**Comment by sssionggg** [comment]
Hi @Wred,

Updated to version 0.2.0.

**Comment by Wred** [comment]
Awesome!  Thanks!

**Pull request merged**
