### PR TITLE
Fix soulmate compatibility

### PR DESCRIPTION
**Pull request by jwarchol**
Siong, these changes are my first stab at bringing Flo into compatibility with the API Soulmate currently provides. I've nested the results one level deeper, and parsed the data coming out of the redis hash. Please have a peak and let me know what you think. 

_This probably shouldn't be merged yet._ I want to do a bit more testing and comparison before I'm confident the compatibility is solid. I'll update this pull req once I'm sure.

### CODE REVIEW

**Comment by sssionggg** [comment]
Hi @jwarchol, do you have any update on this?

**Comment by jwarchol** [comment]
No, sorry. The project got put on the back burner and I haven't been back into it since to do the testing I talked about.

**Comment by sssionggg** [comment]
It's alright.  Thanks.  I will see what I can do with this.

**Comment by sssionggg** [comment]
Hi @jwarchol, I am going to close this pull request since soulmate compatibility isn't the main priority of `flo`.

**Comment by jwarchol** [comment]
Ok, no worries. Thanks again for sharing it.

**Pull request closed without merging**
